#ifndef ADVANCED_NETWORK_H
#define ADVANCED_NETWORK_H


#include <winperformancemetricschecker.h>

DECLARE_PERF_COUNTER_METRIC_CHECKER(AdvancedNetworkDns64Global)
DECLARE_PERF_COUNTER_METRIC_CHECKER(AdvancedNetworkIphttpsGlobal)
DECLARE_PERF_COUNTER_METRIC_CHECKER(AdvancedNetworkSmbServer)
DECLARE_PERF_COUNTER_METRIC_CHECKER(AdvancedNetworkSmbServerShares)
DECLARE_PERF_COUNTER_METRIC_CHECKER(AdvancedNetworkTerminalServices)


#endif // ADVANCED_NETWORK_H
