#ifndef DOTNETCLRJIT_H
#define DOTNETCLRJIT_H

#include <winperformancemetricschecker.h>

DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetClrJit)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetClrLocksAndThreads)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetClrMemory)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetClrRemoting)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetAspNet)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetAspNetApplications)
DECLARE_PERF_COUNTER_METRIC_CHECKER(DotNetAspNetStateService)

#endif // DOTNETCLRJIT_H
