; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OddEye Agent"
#define MyAppVersion "0.5"
#define MyAppExeName "oe-tray-control.exe"
#define MyAppServiceName "agent-service.exe"
#define MyAppTerminalName "oe-terminal.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2BB3A430-E50D-48AA-890C-6988492633A7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\Aram\Documents\OE-Agent\setup\output
OutputBaseFilename=oe-setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{app}\scripts_available"
Name: "{app}\scripts_enabled"

[Files]
Source: "..\build\Control\GuiControl\release\OEAgentControl.exe"; DestDir: "{app}"; Flags: ignoreversion;     DestName: {#MyAppExeName}
Source: "..\build\Control\CuiControl\release\OEConsolController.exe"; DestDir: "{app}"; Flags: ignoreversion; DestName: {#MyAppTerminalName}        
Source: "..\build\Service\release\OE-Agent.exe"; DestDir: "{app}"; Flags: ignoreversion;                      DestName: {#MyAppServiceName}
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\platforms\*";  DestDir: "{app}\platforms"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\conf\*";       DestDir: "{app}\conf"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\libssl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\Qt5Core.dll";  DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\Qt5Gui.dll";   DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\ssleay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppServiceName}"; Parameters: -i
Filename: "{app}\{#MyAppServiceName}";
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{app}\{#MyAppServiceName}"; Parameters: -t
Filename: "{app}\{#MyAppServiceName}"; Parameters: -u 
