; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OddEye Agent"
#define MyAppVersion "0.5"
#define MyAppPublisher "OddEye, Inc."
#define MyAppURL "https://www.oddeye.co/"

#define MyAppExeName "oe-tray-menu.exe"
#define MyAppServiceName "agent-service.exe"
#define MyAppTerminalName "oe-terminal.exe"
#define OddEyeDirName "OddEye Agent"
#define OddEyeDevDir "C:\Users\User\Documents\OE-Agent"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2BB3A430-E50D-48AA-890C-6988492633A7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile={#OddEyeDevDir}\src\setup\LICENSE.TXT
OutputDir={#OddEyeDevDir}\setup\output\
OutputBaseFilename=oe-agent-setup-x86
Compression=lzma
SolidCompression=yes
AppMutex=oe_agent_sys_tray

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{app}\scripts_available"
Name: "{app}\scripts_enabled"

[Files]
Source: "{#OddEyeDevDir}\src\control\build-OESystemTrayController-Desktop_Qt_5_5_0_MSVC2013_32bit-Release\release\OEAgentControl.exe"; DestDir: "{app}"; Flags: ignoreversion;     DestName: {#MyAppExeName}
Source: "{#OddEyeDevDir}\src\control\build-OEConsolController-Desktop_Qt_5_5_0_MSVC2013_32bit-Release\release\OEConsolController.exe"; DestDir: "{app}"; Flags: ignoreversion; DestName: {#MyAppTerminalName}        
Source: "{#OddEyeDevDir}\src\build-OEAgentService-Desktop_Qt_5_5_0_MSVC2013_32bit-Release\release\OE-Agent.exe"; DestDir: "{app}"; Flags: ignoreversion;                      DestName: {#MyAppServiceName}
         
Source: "{#OddEyeDevDir}\setup\bin32\platforms\*";  DestDir: "{app}\platforms"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#OddEyeDevDir}\setup\bin32\conf\*";       DestDir: "{app}\conf"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#OddEyeDevDir}\setup\bin32\scripts_available\*";       DestDir: "{app}\scripts_available"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#OddEyeDevDir}\setup\bin32\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\libssl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\msvcp120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\msvcr120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\Qt5Core.dll";  DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\Qt5Gui.dll";   DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OddEyeDevDir}\setup\bin32\ssleay32.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "C:\Users\Aram\Documents\OE-Agent\setup\bin\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppServiceName}"; Parameters: -i; Flags: runhidden;
Filename: "{app}\{#MyAppServiceName}"; Flags: runhidden;
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\conf\"; Description: "{#StringChange("Open configurations folder", '&', '&&')}"; Flags: shellexec runasoriginaluser nowait postinstall skipifsilent

[UninstallRun]
Filename: "{app}\{#MyAppTerminalName}"; Parameters: -stop; Flags: runhidden;
Filename: "{app}\{#MyAppServiceName}"; Parameters: -t; Flags: runhidden;
Filename: "{app}\{#MyAppServiceName}"; Parameters: -u; Flags: runhidden; 

[Registry]
;current user only
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "OddEye Agent Control"; ValueData: "{app}\{#MyAppExeName}"; 
;Root: HKCU; Subkey: "Software\OddEyeAgent\"; ValueType: string; ValueName: "autostart"; ValueData: false; Flags: uninsdeletekey